### ISSUE TITLE
CSS Formatting

### ISSUE THREAD

**Issue by jim-rosales** [mikeharrell16/bwui-capstone-placeholder#3]
Keep an eye out for your formatting to make sure it is consistent as it improves the readability of your file. 

For example, currently you have:
```CSS
.field select {
  background-color: fff;
  font-size: inherit;
	border-radius: 3px;
  background-color: #fff;
	border: 1px solid #212121;
}
```

With improved formatting:
```CSS
.field select {
  background-color: fff;
  font-size: inherit;
  border-radius: 3px;
  background-color: #fff;
  border: 1px solid #212121;
}
```

https://github.com/mikeharrell16/bwui-capstone-placeholder/blob/a06bd25a9871b2925787b98e24b40812e0f329ca/ware-house-starting-code/resources/css/sell.css#L49-L53
